import os
from datetime import datetime
from pathlib import Path


VEDAI_MD_FILENAME = "VedAI.md"
VEDAI_MAP_FILENAME = "VedAI-map.md"

# File extensions to include in map scan
SCAN_EXTENSIONS = {'.py', '.js', '.ts', '.jsx', '.tsx', '.html', '.css',
                   '.json', '.yaml', '.yml', '.md', '.txt', '.sh', '.bat',
                   '.env', '.toml', '.cfg', '.ini', '.sql'}

# Dirs to skip while scanning
SKIP_DIRS = {'__pycache__', '.git', 'node_modules', '.venv', 'venv',
             'env', '.idea', '.vscode', 'dist', 'build', '.next'}


class ProjectMemory:
    """
    Manages two files in the user's project workspace:

    1. VedAI.md   → Session log (what was done, when, and result)
    2. VedAI-map.md → Project architecture map (what files exist and their roles)

    Workflow:
    - On project connect: both files are created / read
    - Before every task: agent reads both to understand context
    - After every task: both files are updated
    """

    def __init__(self, workspace: str = "."):
        self.workspace = Path(workspace)
        self.filepath = self.workspace / VEDAI_MD_FILENAME
        self.mappath = self.workspace / VEDAI_MAP_FILENAME

    # ──────────────────────────────────────────────────────────────
    # VedAI.md (Session Memory)
    # ──────────────────────────────────────────────────────────────

    def initialize(self, project_name: str = ""):
        """Create VedAI.md if it doesn't exist."""
        name = project_name or self.workspace.name
        if not self.filepath.exists():
            self.workspace.mkdir(parents=True, exist_ok=True)
            content = f"""# VedAI Project Memory
> Auto-generated by VedAI. Do not delete — this file helps the agent remember your project.

## Project: {name}
- **Created**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
- **Workspace**: `{self.workspace}`

---

## Session Log

"""
            self.filepath.write_text(content, encoding="utf-8")

    def read(self) -> str:
        if self.filepath.exists():
            return self.filepath.read_text(encoding="utf-8")
        return ""

    def log_task(self, task: str, plan: str, files_created: list,
                 commands_run: list, status: str):
        """Append task result to VedAI.md and refresh the map."""
        self.initialize()

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        icon = "✅" if status == "success" else "❌"

        section = f"""### {icon} [{timestamp}] {task}

**Status**: {status.upper()}

**Plan Summary**:
{plan[:600]}{'...' if len(plan) > 600 else ''}

"""
        if files_created:
            section += "**Files Created/Modified**:\n"
            for f in files_created:
                section += f"- `{f}`\n"
            section += "\n"

        if commands_run:
            section += "**Commands Executed**:\n"
            for c in commands_run:
                section += f"- `{c}`\n"
            section += "\n"

        section += "---\n\n"

        current = self.filepath.read_text(encoding="utf-8")
        self.filepath.write_text(current + section, encoding="utf-8")

        # Always refresh the map after any task completes
        self.refresh_map()

    def get_session_summary(self) -> str:
        """Return last 3 tasks from VedAI.md for agent context."""
        content = self.read()
        if not content:
            return "Fresh project — no previous sessions."
        task_lines = [l for l in content.split("\n") if l.startswith("### ")]
        if not task_lines:
            return "Project started. No tasks logged yet."
        return "Recent tasks:\n" + "\n".join(task_lines[-3:])

    # ──────────────────────────────────────────────────────────────
    # VedAI-map.md (Project Architecture Map)
    # ──────────────────────────────────────────────────────────────

    def refresh_map(self):
        """Scan workspace and rewrite VedAI-map.md with full project structure."""
        tree_lines = []
        file_registry = []

        for root, dirs, files in os.walk(self.workspace):
            # Prune skip dirs in-place
            dirs[:] = [d for d in sorted(dirs) if d not in SKIP_DIRS and not d.startswith('.')]

            rel_root = Path(root).relative_to(self.workspace)
            depth = len(rel_root.parts)

            if depth > 0:
                indent = "  " * (depth - 1)
                folder_name = Path(root).name
                tree_lines.append(f"{indent}📁 **{folder_name}/**")

            for fname in sorted(files):
                ext = Path(fname).suffix.lower()
                if ext not in SCAN_EXTENSIONS:
                    continue
                rel_path = (rel_root / fname).as_posix()
                file_indent = "  " * depth
                icon = self._file_icon(fname)
                tree_lines.append(f"{file_indent}{icon} `{fname}`")
                file_registry.append(rel_path)

        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        content = f"""# VedAI Project Map
> Auto-generated by VedAI. Updated on every task. Do not delete.

**Project**: `{self.workspace.name}`
**Last Scanned**: {now}
**Total Files Tracked**: {len(file_registry)}

---

## Directory Structure

```
{chr(10).join(tree_lines) if tree_lines else "Empty project"}
```

---

## All Tracked Files

{chr(10).join(f"- `{f}`" for f in file_registry) if file_registry else "No files yet."}

---
*This map is automatically updated after every VedAI task.*
"""
        self.mappath.write_text(content, encoding="utf-8")

    def read_map(self) -> str:
        if self.mappath.exists():
            return self.mappath.read_text(encoding="utf-8")
        return "Map not yet generated. Will be created on project connect."

    def get_map_summary(self) -> str:
        """Return a short project structure summary for agent context."""
        if not self.mappath.exists():
            return "No project map yet."
        content = self.read_map()
        # Extract just the tracked files list (compact)
        lines = content.split("\n")
        file_lines = [l for l in lines if l.startswith("- `")]
        total = len(file_lines)
        preview = "\n".join(file_lines[:20])
        suffix = f"\n...and {total - 20} more files." if total > 20 else ""
        return f"Project has {total} tracked file(s):\n{preview}{suffix}"

    # ──────────────────────────────────────────────────────────────
    # Combined context for agent (read before EVERY task)
    # ──────────────────────────────────────────────────────────────

    def build_agent_context(self) -> str:
        """
        Called before every task. Returns:
        - VedAI-map.md summary (what exists in the project)
        - VedAI.md summary (what was done before)
        """
        map_ctx = self.get_map_summary()
        session_ctx = self.get_session_summary()

        return f"""## Project Map (VedAI-map.md)
{map_ctx}

## Past Session Memory (VedAI.md)
{session_ctx}
"""

    # ──────────────────────────────────────────────────────────────
    # Helpers
    # ──────────────────────────────────────────────────────────────

    @staticmethod
    def _file_icon(filename: str) -> str:
        ext = filename.rsplit('.', 1)[-1].lower()
        icons = {
            'py': '🐍', 'js': '🟨', 'ts': '🔷', 'jsx': '⚛️', 'tsx': '⚛️',
            'html': '🌐', 'css': '🎨', 'json': '📋', 'md': '📝',
            'yaml': '⚙️', 'yml': '⚙️', 'sh': '⚡', 'bat': '⚡',
            'sql': '🗄️', 'env': '🔐', 'txt': '📄'
        }
        return icons.get(ext, '📄')
