import os
from datetime import datetime
from pathlib import Path


VEDAI_MD_FILENAME = "VedAI.md"


class ProjectMemory:
    """
    Manages the VedAI.md file in the user's project workspace.
    This acts as the agent's long-term memory — it logs every task,
    every file created, and every command run, so the agent knows
    what it has already done in future sessions.
    """

    def __init__(self, workspace: str = "."):
        self.workspace = Path(workspace)
        self.filepath = self.workspace / VEDAI_MD_FILENAME

    def initialize(self, project_name: str = "My Project"):
        """Create VedAI.md if it doesn't exist."""
        if not self.filepath.exists():
            self.workspace.mkdir(parents=True, exist_ok=True)
            content = f"""# VedAI Project Memory
> Auto-generated by VedAI. Do not delete — this file helps the agent remember your project.

## Project: {project_name}
- **Created**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
- **Agent**: VedAI Autonomous Studio

---

## Session Log

"""
            self.filepath.write_text(content, encoding="utf-8")
            return f"✅ VedAI.md created at {self.filepath}"
        return f"📄 VedAI.md already exists at {self.filepath}"

    def read(self) -> str:
        """Read the current memory file."""
        if self.filepath.exists():
            return self.filepath.read_text(encoding="utf-8")
        return ""

    def log_task(self, task: str, plan: str, files_created: list, commands_run: list, status: str):
        """Append a completed task to VedAI.md."""
        self.initialize()

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        icon = "✅" if status == "success" else "❌"

        section = f"""### {icon} [{timestamp}] Task: {task}

**Status**: {status.upper()}

**Plan Summary**:
{plan[:500]}{'...' if len(plan) > 500 else ''}

"""
        if files_created:
            section += "**Files Created/Modified**:\n"
            for f in files_created:
                section += f"- `{f}`\n"
            section += "\n"

        if commands_run:
            section += "**Commands Executed**:\n"
            for c in commands_run:
                section += f"- `{c}`\n"
            section += "\n"

        section += "---\n\n"

        # Append to file
        current = self.filepath.read_text(encoding="utf-8")
        self.filepath.write_text(current + section, encoding="utf-8")

    def get_context_summary(self) -> str:
        """Return a short summary of past work for the agent's context."""
        content = self.read()
        if not content:
            return "No previous work found. This is a fresh project."

        # Extract last 3 task entries as context
        lines = content.split("\n")
        task_lines = [l for l in lines if l.startswith("### ")]
        if not task_lines:
            return "Project started. No tasks completed yet."

        recent = task_lines[-3:]
        return f"Previous work in this project:\n" + "\n".join(recent)
